// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureAndTranslate(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CaptureAndTranslate'](arg1, arg2, arg3, arg4, arg5);
}

export function CaptureRegion(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CaptureRegion'](arg1, arg2, arg3, arg4);
}

export function Translate(arg1, arg2) {
  return window['go']['main']['App']['Translate'](arg1, arg2);
}
